services:
  knowledge_reinforce:
    build:
      context: .
    container_name: knowledge_reinforce
    environment:
      - DB_NAME=knowledge_reinforce
      - DB_HOST=knowledge_reinforce_db
      - DB_USER=root
      - DB_PASSWORD=strongpassword
    volumes:
      - ./app:/app
  knowledge_reinforce_db:
    image: 'mysql:latest'
    container_name: knowledge_reinforce_db
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
    ports:
      - '3684:3306'